// src/utils/uuid.ts
import { v7 as uuidv7, validate as uuidValidate, version as uuidVersion } from 'uuid';

/**
 * Generate a UUID v7 (time-ordered, lexicographically sortable).
 *
 * v7 encodes a millisecond-precision Unix timestamp in the first 48 bits,
 * which means rows inserted later will always sort after rows inserted earlier —
 * ideal for SQL primary keys (natural ordering without a secondary index) and
 * for MongoDB document IDs when you want predictable cursor-based pagination.
 *
 * Format: xxxxxxxx-xxxx-7xxx-yxxx-xxxxxxxxxxxx
 * Example: 019e29a8-7b9f-7209-bf7c-9fa84a4f3a74
 */
export function generateUid(): string {
    return uuidv7();
}

/**
 * Alias for SQL primary keys — documents intent at the call site.
 * Identical implementation to generateUid() but reads better in repository code:
 *
 *   const id = generateSqlId();  // clearly a PK for a SQL row
 */
export const generateSqlId = generateUid;

/**
 * Generate N UUID v7s in one call, preserving monotonic ordering.
 * Useful when bulk-inserting rows and you need each PK pre-generated.
 */
export function generateUids(count: number): string[] {
    return Array.from({ length: count }, () => uuidv7());
}

/**
 * Returns true if the string is a structurally valid UUID (any version).
 * Use this at API boundaries before forwarding an ID to the database.
 */
export function isValidUid(id: string): boolean {
    return uuidValidate(id);
}

/**
 * Returns true only for UUID v7 (time-ordered variant).
 * Useful in tests to assert that IDs were generated by this module.
 */
export function isUidV7(id: string): boolean {
    return uuidValidate(id) && uuidVersion(id) === 7;
}

/**
 * Extract the embedded timestamp from a UUID v7.
 * The first 48 bits encode milliseconds since Unix epoch.
 * Returns null for non-v7 UUIDs (v4, v1, etc.).
 */
export function getTimestampFromUid(id: string): Date | null {
    if (!isUidV7(id)) return null;
    const timestampMs = parseInt(id.substring(0, 12), 16);
    return new Date(timestampMs);
}

/**
 * Sort an array of UUIDs. Since v7 is time-ordered, this doubles as
 * a chronological sort for v7 IDs without any extra metadata.
 */
export function sortUids(uids: string[], ascending = true): string[] {
    return [...uids].sort((a, b) =>
        ascending ? a.localeCompare(b) : b.localeCompare(a)
    );
}